version: '3.2'

services:
  grafana:
    image: grafana/grafana:8.4.6
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/provisioning/datasources:/etc/grafana/provisioning/datasources/
      - ./config/provisioning/dashboards:/etc/grafana/dashboards/
      - ./config/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    networks:
      - traefik-public
      - monitoring-public
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
      placement:
        constraints: [node.role == manager]
      labels:
        - traefik.enable=true
        - traefik.docker.network=traefik-public
        - traefik.constraint-label=traefik-public
        - traefik.http.routers.grafana.entrypoints=http, https
        - traefik.http.routers.grafana.middlewares=cors-headers@file
        - traefik.http.routers.grafana.rule=Host(`{{ grafana_domain }}`)
        - traefik.http.routers.grafana.tls=true
        - traefik.http.routers.grafana.tls.certresolver={{ traefik_tls_certresolver }}
        - traefik.http.services.grafana-service.loadbalancer.server.port=3000

networks:
  # Use the previously created public network "traefik-public", shared with other
  # services that need to be publicly available via this Traefik
  traefik-public:
    external: true

  monitoring-public:
    external: true

volumes:
  grafana-data:
    driver: local